/**
 * work-strings.ts — Locale bundle for auto-filed Work System issue text.
 *
 * Everything the Work System writes into a GitHub issue BODY goes through
 * `t(lang, key, vars)`. Labels (`Type:*`, `Status:*`, `Priority:*`, `Property:*`,
 * `Agent:*`) and the bracketed title prefixes (`[Goal]`, `[Sweep]`,
 * `[Project-Check]`, `[BPE]`, `[Native]`, `[Reminder]`, `[Research]`, `[Queue]`)
 * are classification tokens, not prose — they are never routed through this
 * module and stay in English regardless of locale (dedup keys and the Pulse
 * kanban badge logic depend on them).
 *
 * Design contract:
 *   - Key-level fallback. A locale bundle only needs to cover the keys it has
 *     a translation for; anything missing (or a whole missing locale file)
 *     falls back to the built-in `EN` bundle. Never throws.
 *   - `EN` below is the single source of truth for the key set — every other
 *     locale is a partial override of it. `LIFEOS/TOOLS/InitWorkLocale.ts`
 *     reads `EN`'s keys to generate/validate locale files; nothing else does.
 *   - Interpolation is `{name}` literal substitution only — no expressions,
 *     no plural rules, no nested key references. Translators who need to work
 *     around English pluralization (`{age} days`) phrase around the count
 *     instead (see USER/CONFIG/locales/README.md).
 *   - Locale files live at `<userDir>/CONFIG/locales/<lang>.json` — an
 *     INTERFACE path (LIFEOS/DOCUMENTATION/SystemUserBoundary.md § INTERFACE),
 *     resolved via `paiUserDir()` (LIFEOS/TOOLS/LifeosConfig.ts), never a
 *     literal `LIFEOS/USER/...` string.
 *
 * Consumers:
 *   - LIFEOS/TOOLS/WorkSweep.ts     — 4 sub-sweep issue bodies
 *   - hooks/ReminderRouter.hook.ts  — reminder/research/queue issue bodies
 *   - LIFEOS/TOOLS/InitWorkLocale.ts — locale scaffold/check CLI (reads EN only)
 */

import { existsSync, readFileSync } from "fs";
import { join } from "path";
import { paiUserDir } from "../../LIFEOS/TOOLS/LifeosConfig";

export type IssueLang = string;

// The built-in English bundle. This is a byte-for-byte port of the strings
// that used to be hardcoded inline in WorkSweep.ts / ReminderRouter.hook.ts —
// when `WORK.ISSUE_LANGUAGE` is unset (or "en"), output is unchanged.
export const EN: Record<string, string> = {
  "sweep.session.header": "## 🧹 Captured by WorkSweep",
  "sweep.session.goalLine": "\n> 🎯 **Principal stated goal:** {goal}\n",
  "sweep.session.table":
    "| Field | Value |\n" +
    "|-------|-------|\n" +
    "| **Task** | {task} |\n" +
    "| **Effort** | {effort} |\n" +
    "| **Mode** | {mode} |\n" +
    "| **Phase** | {phase} |\n" +
    "| **Project** | {project} |\n" +
    "| **Slug** | `{slug}` |\n" +
    "| **ISA** | `{isaPath}` |\n" +
    "| **Updated** | {updated} |",
  "sweep.session.footerNative": "*Auto-captured by LifeOS WorkSweep (NATIVE-mode session with artifacts)*",
  "sweep.session.footerAlgorithm": "*Auto-captured by LifeOS WorkSweep (untracked Algorithm session)*",

  "sweep.projectCheck.titleSuffix": "no commits in {age} days",
  "sweep.projectCheck.body":
    "## 🧹 Project Check\n\n" +
    "**Project:** {project}\n" +
    "**Path:** `{path}`\n" +
    "**Last commit:** {age} days ago\n\n" +
    "Is this project paused, complete, or just slow? If active, push a commit or close this. If paused, label `Status:blocked` with reason. If done, close.",

  "sweep.goal.body":
    "## 🎯 TELOS Goal\n\n" +
    "**Goal:** {id} — {text}\n\n" +
    "This goal is in your active TELOS but has no matching open issue. Pick a concrete next action, break it down, or close this if the goal needs to be deferred.\n\n" +
    "Source: `LIFEOS/USER/TELOS/PRINCIPAL_TELOS.md` → `## Active Goals`",

  "sweep.bpe.titleNever": "never run",
  "sweep.bpe.titleOverdue": "{days}d since last (cadence {cadenceDays}d)",
  "sweep.bpe.never": "never",
  "sweep.bpe.daysAgo": "{days} days ago",
  "sweep.bpe.body":
    "## 🪓 Scheduled BitterPillEngineering pass\n\n" +
    "As model capability rises, the healthy line (right amount of scaffolding) DROPS — but the actual line keeps climbing, because adding feels productive and pruning feels like nothing. The gap widens unless subtraction is scheduled. This is that schedule.\n\n" +
    "**Run:** `Skill(\"BitterPillEngineering\", \"audit\")` over the {targets}.\n" +
    "**Cadence:** every {cadenceDays} days. Last audit: {lastAudit}.\n" +
    "**Then stamp it:** `bun ~/.claude/LIFEOS/TOOLS/WorkSweep.ts --stamp-bpe` to reset the clock.\n\n" +
    "Propose-only — never auto-cut. A cut needs judgment + ratification (the producer-lock / shadow-log call is why).",

  "sweep.footer": "*Auto-generated by LifeOS WorkSweep*",

  "reminder.header": "## {prefix} captured by LifeOS",
  "reminder.trigger": "**Trigger:** `{imperative}`",
  "reminder.kind": "**Kind:** {kind}",
  "reminder.due": "\n**Due:** {due}\n",
  "reminder.originalPrompt": "### Original prompt",
  "reminder.footer": "*Auto-routed by LifeOS ReminderRouter hook (UserPromptSubmit).*",

  "kind.reminder": "reminder",
  "kind.research": "research",
  "kind.queue": "queue",
};

// One-entry-per-lang cache for the current process. Hooks run once per
// prompt/sweep invocation (short-lived processes), so this only saves
// repeat lookups within a single sweep run's multiple issue bodies.
const bundleCache = new Map<string, Record<string, string> | null>();

// Resolves and parses a locale bundle. Never throws — any failure (missing
// file, malformed JSON, non-object contents) is treated as "no overrides",
// which falls back to EN for every key. This mirrors the fail-open contract
// hooks/lib/work-config.ts already uses for repo-config breakage.
function loadLocaleBundle(lang: IssueLang): Record<string, string> | null {
  if (bundleCache.has(lang)) return bundleCache.get(lang)!;
  let bundle: Record<string, string> | null = null;
  try {
    const path = join(paiUserDir(), "CONFIG", "locales", `${lang}.json`);
    if (existsSync(path)) {
      const raw = JSON.parse(readFileSync(path, "utf-8"));
      if (raw && typeof raw === "object" && !Array.isArray(raw)) {
        bundle = raw as Record<string, string>;
      }
    }
  } catch {
    bundle = null;
  }
  bundleCache.set(lang, bundle);
  return bundle;
}

function interpolate(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (whole, name) => {
    const v = vars[name];
    return v === undefined ? whole : String(v);
  });
}

/**
 * Resolves `key` for `lang`, falling back to EN for missing locales, missing
 * files, malformed JSON, and missing keys within an otherwise-loaded bundle
 * (key-level fallback — a locale can translate one key and leave the rest).
 * Falls back to the raw key string itself if even EN doesn't have it, so a
 * caller typo never throws mid-hook.
 */
export function t(lang: IssueLang, key: string, vars: Record<string, string | number> = {}): string {
  const bundle = lang && lang !== "en" ? loadLocaleBundle(lang) : null;
  const raw = (bundle && typeof bundle[key] === "string" ? bundle[key] : undefined) ?? EN[key] ?? key;
  return interpolate(raw, vars);
}

// ── CLI smoke ────────────────────────────────────────────────────────────────

if (import.meta.main) {
  const [lang, key] = process.argv.slice(2);
  if (!lang || !key) {
    console.log("usage: bun work-strings.ts <lang> <key> [key=value ...]");
    process.exit(lang && key ? 0 : 1);
  }
  const vars: Record<string, string> = {};
  for (const pair of process.argv.slice(4)) {
    const eq = pair.indexOf("=");
    if (eq > 0) vars[pair.slice(0, eq)] = pair.slice(eq + 1);
  }
  console.log(t(lang, key, vars));
}
